### ISSUE TITLE
Issue Seo By Yoast v.7.5.1

### ISSUE THREAD

**Issue by Fabiato** [harryfinn/yoast-cmb2-field-analysis#11]
Console log error:

ReferenceError: yoastWebpackJsonp is not defined
wp-seo-replacevar-plugin-751.min.js:1:1
ReferenceError: YoastReplaceVarPlugin is not defined
wp-seo-post-scraper-751.min.js:33:931983
ReferenceError: YoastSEO is not defined

**Comment by harryfinn** [comment]
This should also be fixed by PR #13

**Comment by Fabiato** [comment]
Thanks!
Cheers
