### ISSUE TITLE
Failed to activate plugin due to CMB2 being already bootstrapped by another plugin 

### ISSUE THREAD

**Issue by monecchi** [harryfinn/yoast-cmb2-field-analysis#2]
Hi there. This looks like a very promising solution for adding CMB2 custom fields to Yoast WP Seo Analysis. Unfortunately, I couldn't get it activated because my theme is bundled with a plugin which also requires CMB2. Any chances to get a workaround function in order to see if CMB2 is already being bootstrapped by another plugin or the theme itself?

The plugin will also fail to activate if the theme uses the Premium version of  WordPress Seo by Yoast. I've fixed it with a dirty hack by changing the function around line 49 checking for `wordpress-seo-premium` instead:

```
public function check_for_yoast_seo() {
    if(!is_plugin_active('wordpress-seo-premium/wp-seo-premium.php')) {
    add_action('admin_notices', [$this, 'require_yoast_message']);

    return true;
}

    return false;
}
```

Thanks in advance.

**Comment by monecchi** [comment]
Hi again. I've managed to activate the plugin in a very tricky way.

What I did was to extract a bit of functions from a Genesis Framework theme that checks for plugins in the form of an array.

My theme comes with CMB2 bundled within another plugin, and that was causing **yoast-cmb2-field-analysis** to fail on activation. This might also happen if CMB2 is bootstrapped within the theme itself rather than a plugin dependency.

```
/**
* Detect plugin by constant, class or function existence.
*
* @since 1.6.0
*
* @param array $plugins Array of array for constants, classes and / or
* functions to check for plugin existence.
* @return boolean True if plugin exists or false if plugin constant, class or
* function not detected.
*/
function yoast_cmb2_detect_plugins( $plugins ) {

/** Check for classes */
if ( isset( $plugins['classes'] ) ) {
    foreach ( $plugins['classes'] as $name ) {
    if ( class_exists( $name ) )
        return true;
    }
}

/** Check for functions */
if ( isset( $plugins['functions'] ) ) {
    foreach ( $plugins['functions'] as $name ) {
    if ( function_exists( $name ) )
        return true;
    }
}

/** Check for constants */
  if ( isset( $plugins['constants'] ) ) {
    foreach ( $plugins['constants'] as $name ) {
    if ( defined( $name ) )
        return true;
    }
}

/** No class, function or constant found to exist */
return false;

}
```

--//--

```
/**
    * Detect required Plugins that add constants, classes or functions.
    *
    * Uses yoast_cmb2_check_required_plugins filter to allow third party manpulation of SEO
    * plugin list.
    *
    * @since 1.6.0
    *
    * @uses yoast_cmb2_detect_plugins()
    *
    * @return boolean True if plugin exists or false if plugin constant, class or function not detected.
    */
function yoast_cmb2_check_required_plugins() {

  return  (
    // Use this filter to adjust plugin tests.
    apply_filters(
      'yoast_cmb2_check_plugins',
      /** Add to this array to add new plugin checks. */
      array(
        // Classes to detect.
        'classes' => array(
          'WPSEO_Premium',
          'wpSEO',
        ),

        // Functions to detect.
        'functions' => array(
          'CMB2',
          'wpseo_init',
        ),

        // Constants to detect.
        'constants' => array( 'WPSEO_VERSION', 'CMB2_LOADED', ),
      )
    )
  );

}
```

**Comment by harryfinn** [comment]
Hi @monecchi, thanks for your comments around this issue, I should have noted in the readme that this was initially only designed to work with the free version of Yoast SEO. I'll setup a separate branch and implement some fixes around the issues you've described. Perhaps you'd then be able to test this with me in your setup as well before it's merged into a new release?

**Comment by monecchi** [comment]
Thanks for the response. For sure! I'll keep subscribed, so please let me know when it's ready.

My issue was not being able to use the plugin at all, because it wouldn't activate. The hack I've applied worked allowing me to use the plugin, however, it skipped any activation / deactivation steps.

Also, my theme manages CMB2 meta boxes with a custom prefix, so I had to edit `yoast-cmb2-field-analysis.js` in order to include those custom prefixes as the input names, e.g using prefix named `_wptheme_` and then changed it to  `input[type=text][name*=_wptheme_]`, `textarea[name*=_wptheme_]`

Although I've successfully managed to make those changes, I've just noticed the plugin does not enqueues `yoast-cmb2-field-analysis.js` while editing a post, so it sadly means the plugin does not seem to work for me.

I'll keep inspecting in order to see if I can get it to work.

Regards,

Adriano.

**Comment by harryfinn** [comment]
Hi @monecchi - Sorry for a rather long quiet period on this issue, have finally gotten around to updating this plugin which checks for the premium plugin and also a different method for checking if CMB2 is already loaded, hopefully this will resolve these two issues for you.

I've also created a new issue (#4) regarding the ability to add a custom prefix, which I will get to work on shortly!

**Comment by monecchi** [comment]
Hey @harryfinn! That's great news! I'll give it another try again, I'm really sure a lot of people will find it great also. Thanks for keeping us updated!

**Comment by monecchi** [comment]
Hi again @harryfinn. I've just tested it and can confirm it works out of the box now! Thanks! 👍 

The only issue though is the lack of an option to set a custom prefix.

No problem though if building a theme or plugin with CBM2 from start as one could simply add `_CMB2_` as a prefix to his fields as instructed.

I'll keep watching for that!
